In [66]:
import torch
import numpy as np
import matplotlib.pyplot as plt

In [124]:
torch.tensor([4,2],dtype=torch.float64)
tpl = 1000
torch.tensor([tpl/7397, tpl/7662, tpl/2615, tpl/1942, tpl/3117, tpl/1469, tpl/821, tpl/965, tpl/1120, tpl/211],dtype=torch.float64)


tensor([0.1352, 0.1305, 0.3824, 0.5149, 0.3208, 0.6807, 1.2180, 1.0363, 0.8929,
        4.7393], dtype=torch.float64)

In [67]:
prediction = torch.load('../hpc-tensors/Best_prediction_1.pt')
prediction = torch.cat((prediction,torch.load('../hpc-tensors/Best_prediction_2.pt')),dim=0)
prediction = torch.cat((prediction,torch.load('../hpc-tensors/Best_prediction_3.pt')),dim=0)
prediction = torch.cat((prediction,torch.load('../hpc-tensors/Best_prediction_4.pt')),dim=0)

targets = torch.load('../hpc-tensors/Targes_1.pt')
targets = torch.cat((targets,torch.load('../hpc-tensors/Targes_2.pt')),dim=0)
targets = torch.cat((targets,torch.load('../hpc-tensors/Targes_3.pt')),dim=0)
targets = torch.cat((targets,torch.load('../hpc-tensors/Targes_4.pt')),dim=0)

prepredictions = torch.load('../hpc-tensors/Best_postpredictions_1.pt')
print(prepredictions.size())
prepredictions = torch.cat((prepredictions,torch.load('../hpc-tensors/Best_postpredictions_2.pt')),dim=0)
prepredictions = torch.cat((prepredictions,torch.load('../hpc-tensors/Best_postpredictions_3.pt')),dim=0)
prepredictions = torch.cat((prepredictions,torch.load('../hpc-tensors/Best_postpredictions_4.pt')),dim=0)



torch.Size([5248, 10])


In [118]:
for index in range(targets.size()[1]):
    print(targets[:,index].sum())
print(targets.sum())

tensor(7397)
tensor(7662)
tensor(2615)
tensor(1942)
tensor(3117)
tensor(1469)
tensor(821)
tensor(965)
tensor(1120)
tensor(211)
tensor(27319)


In [68]:
print(prediction.size())
print(targets.size())
print(prepredictions.size())
print(prepredictions)
print(prediction)
#prepredictions = prepredictions.transpose(0,1)

torch.Size([21504, 10])
torch.Size([21504, 10])
torch.Size([21504, 10])
tensor([[4.6317e-01, 7.0194e-01, 3.5376e-03,  ..., 6.6159e-02, 8.6449e-02,
         2.3258e-03],
        [1.6685e-01, 8.2820e-01, 7.0374e-03,  ..., 2.1822e-01, 9.4196e-02,
         3.0286e-05],
        [1.0480e-01, 8.2496e-01, 6.3242e-03,  ..., 2.0515e-01, 7.4765e-02,
         1.2892e-07],
        ...,
        [6.4046e-01, 3.9636e-01, 6.2294e-03,  ..., 1.8589e-02, 5.1601e-02,
         1.0760e-02],
        [1.5586e-01, 1.0998e-01, 1.2961e-02,  ..., 2.5984e-01, 2.1526e-02,
         1.7091e-05],
        [1.0863e-01, 1.2351e-02, 9.9786e-01,  ..., 4.5914e-05, 4.1330e-06,
         3.2062e-18]])
tensor([[0, 1, 0,  ..., 0, 0, 0],
        [0, 1, 0,  ..., 0, 0, 0],
        [0, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 1,  ..., 0, 0, 0]], dtype=torch.int32)


In [69]:
65792/21504

3.0595238095238093

In [70]:
for i in range(prediction.size()[1]):
    print(f'Pred:\t{prediction[:,i:i+1].sum()}')
    print(f'Target:\t{targets[:,i:i+1].sum()}')

Pred:	6577
Target:	7397
Pred:	8996
Target:	7662
Pred:	2779
Target:	2615
Pred:	1843
Target:	1942
Pred:	2485
Target:	3117
Pred:	1131
Target:	1469
Pred:	769
Target:	821
Pred:	176
Target:	965
Pred:	109
Target:	1120
Pred:	0
Target:	211


In [71]:
confusionmatrix = np.zeros((4,10), dtype=int)
print(confusionmatrix)
print(prediction.size()[0] == targets.size()[0])

# Make a confusionmattix that contains (in rows):
# 1. count of number of times each positive label (1) was correctly predicted labels.
# 2. count of number of times each negativ label (0) was correctly predicted labels. 
# 3. the number of time each label was predicted, but was not there
# 4. the number of times each label was there, but was not predicted.

# This was done of each of the 10 sublocation

for i in range(prediction.size()[1]):
    for j in range(prediction.size()[0]):
        # 1.
        if prediction[j,i] == 1 and targets[j,i] == 1:
            confusionmatrix[0,i] += 1
        # 2.
        elif prediction[j,i] == 0 and targets[j,i] == 0:
            confusionmatrix[1,i] += 1
        # 3.
        elif prediction[j,i] == 1 and targets[j,i] == 0:
            confusionmatrix[2,i] += 1
        elif prediction[j,i] == 0 and targets[j,i] == 1:
            confusionmatrix[3,i] += 1

confusionmatrix

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
True


array([[ 4825,  5896,  2293,  1357,  1767,   542,   626,    92,    23,
            0],
       [12355, 10742, 18403, 19076, 17669, 19446, 20540, 20455, 20298,
        21293],
       [ 1752,  3100,   486,   486,   718,   589,   143,    84,    86,
            0],
       [ 2572,  1766,   322,   585,  1350,   927,   195,   873,  1097,
          211]])

In [72]:
Highlevel_list = ['Nucleus','Cytoplasm','Extracellular','Mitochondrion','Cell membrane','Endoplasmic reticulum','Plastid','Golgi apparatus','Lysosome/Vacuole','Peroxisome']
    
#for j in range(len(Highlevel_list)):
#    print(Highlevel_list[j],end='\t')
for i in range(4):
    for j in range(len(Highlevel_list)):
        print(confusionmatrix[i,j],end='\t')
    print()

4825	5896	2293	1357	1767	542	626	92	23	0	
12355	10742	18403	19076	17669	19446	20540	20455	20298	21293	
1752	3100	486	486	718	589	143	84	86	0	
2572	1766	322	585	1350	927	195	873	1097	211	


In [73]:
Highlevel_list = ['Nucleus','Cytoplasm','Extracellular','Mitochondrion','Cell membrane','Endoplasmic reticulum','Plastid','Golgi apparatus','Lysosome/Vacuole','Peroxisome']
    
#for j in range(len(Highlevel_list)):
#    print(Highlevel_list[j],end='\t')
for i in [0,2,3]:
    for j in range(len(Highlevel_list)):
        print(confusionmatrix[i,j],end='\t')
    print()

# 1. Correctly predicted to be precent
# 2. the number of time each label was predicted, but was not there
# 3. the number of times each label was there, but was not predicted.

4825	5896	2293	1357	1767	542	626	92	23	0	
1752	3100	486	486	718	589	143	84	86	0	
2572	1766	322	585	1350	927	195	873	1097	211	


In [74]:
prediction.size()[1]

10

In [75]:
confusionmatrix_Nucleus_Cytoplasm = []
for i in range(4):
    confusionmatrix_Nucleus_Cytoplasm.append(0)
print(confusionmatrix_Nucleus_Cytoplasm)   

If_predicted = False
for j in range(prediction.size()[0]):
    # predicted?
    If_predicted = False
    if prediction[j,0] == 1 and prediction[j,1] == 1:
        If_predicted = True
        
    # Was it there?
    if targets[j,0] == 1 and targets[j,1] == 1:
        if If_predicted:
            confusionmatrix_Nucleus_Cytoplasm[0] += 1 #TP
        else:
            confusionmatrix_Nucleus_Cytoplasm[2] += 1 #FN
    else:
        if If_predicted:
            confusionmatrix_Nucleus_Cytoplasm[3] += 1 #FP
        else:
            confusionmatrix_Nucleus_Cytoplasm[1] += 1 #TN
print(confusionmatrix_Nucleus_Cytoplasm)

[0, 0, 0, 0]
[1027, 16274, 2069, 2134]


In [76]:
# Make a confusionmattix that contains (in rows):
# 1. count of number of times each positive label (1) was correctly predicted labels.
# 2. count of number of times each negativ label (0) was correctly predicted labels. 
# 3. the number of time each label was predicted, but was not there
# 4. the number of times each label was there, but was not predicted.

# This was done of each of the 10 sublocation

for i in range(4):
    if i == 0:
        print('TP',end='\t')
    elif i == 1:
        print('TN',end='\t')
    elif i == 2:
        print('FP',end='\t')
    elif i == 3:
        print('FN',end='\t')
    
    for j in range(len(Highlevel_list)):
        print(confusionmatrix[i,j],end='\t')
    print(confusionmatrix_Nucleus_Cytoplasm[i],end='\t')
    print()


TP	4825	5896	2293	1357	1767	542	626	92	23	0	1027	
TN	12355	10742	18403	19076	17669	19446	20540	20455	20298	21293	16274	
FP	1752	3100	486	486	718	589	143	84	86	0	2069	
FN	2572	1766	322	585	1350	927	195	873	1097	211	2134	


In [77]:
for j in range(len(Highlevel_list)):

    print(Highlevel_list[j],end=': ')

Nucleus: Cytoplasm: Extracellular: Mitochondrion: Cell membrane: Endoplasmic reticulum: Plastid: Golgi apparatus: Lysosome/Vacuole: Peroxisome: 

In [78]:
count_number_pred = []
count_number_targets = []
for loc_count in range(10):
    count_number_pred.append(0)
    count_number_targets.append(0)


for i in range(prediction.size()[0]):
    for loc_count in range(10):
        if prediction[i].sum() == loc_count:
            count_number_pred[loc_count] += 1
        if targets[i].sum() == loc_count:
            count_number_targets[loc_count] += 1

In [79]:
count_number_pred

[0, 18143, 3361, 0, 0, 0, 0, 0, 0, 0]

In [80]:
count_number_targets

[0, 16418, 4495, 471, 102, 18, 0, 0, 0, 0]

In [81]:
print('Precision')
for j in range(len(Highlevel_list)):
    print(f'{confusionmatrix[0,j]/(confusionmatrix[0,j]+confusionmatrix[2,j]):.3f}',end='\t')
print()
print('Recall')
for j in range(len(Highlevel_list)):
    print(f'{confusionmatrix[0,j]/(confusionmatrix[0,j]+confusionmatrix[3,j]):.3f}',end='\t')
print() 
print('Accuracy')
for j in range(len(Highlevel_list)):
    Tp = confusionmatrix[0,j]
    Tn = confusionmatrix[1,j]
    acc = (Tp+Tn) / (confusionmatrix[:,j].sum())
    print(f'{acc:.3f}',end='\t')
    
    
print() 
print('F1')
for j in range(len(Highlevel_list)):
    p = confusionmatrix[0,j]/(confusionmatrix[0,j]+confusionmatrix[2,j])
    r = confusionmatrix[0,j]/(confusionmatrix[0,j]+confusionmatrix[3,j])
    print(f'{2*p*r/(p+r):.3f}',end='\t')


Precision
0.734	0.655	0.825	0.736	0.711	0.479	0.814	0.523	0.211	

C:\Users\morte\Anaconda3\envs\Master\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in long_scalars
  This is separate from the ipykernel package so we can avoid doing imports until


nan	
Recall
0.652	0.770	0.877	0.699	0.567	0.369	0.762	0.095	0.021	0.000	
Accuracy
0.799	0.774	0.962	0.950	0.904	0.930	0.984	0.955	0.945	0.990	
F1
0.691	0.708	0.850	0.717	0.631	0.417	0.787	0.161	0.037	

C:\Users\morte\Anaconda3\envs\Master\lib\site-packages\ipykernel_launcher.py:20: RuntimeWarning: invalid value encountered in long_scalars


nan	

In [82]:
Precision
0.660	0.638	0.677	0.476	0.513	0.245	0.300	0.111	0.102	0.030	
Recall
0.777	0.809	0.929	0.801	0.709	0.776	0.912	0.734	0.792	0.735	
Accuracy
0.786	0.768	0.938	0.902	0.860	0.822	0.915	0.724	0.624	0.762	
F1
0.714	0.713	0.783	0.597	0.595	0.373	0.451	0.192	0.180	0.057	


confusionmatrix[:,0]

array([ 4825, 12355,  1752,  2572])

In [83]:
prepredictions.size()

torch.Size([21504, 10])

In [102]:
import pylustrator
from sklearn.metrics import roc_auc_score, precision_recall_curve, average_precision_score
from sklearn.metrics import roc_curve, auc


In [85]:
#make AOC graphs for all locations!!!
#numpy.random.uniform(low=0.0, high=1.0, size=None)¶
#pylustrator.start()
#print(prepredictions)
#print(targets)
Highlevel_list = ['Nucleus','Cytoplasm','Extracellular','Mitochondrion','Cell membrane','Endoplasmic reticulum','Plastid','Golgi apparatus','Lysosome_Vacuole','Peroxisome']
tensor_row_length = prepredictions.size()[0]
#print(prepredictions)

best_thresholds = []
for i in range(10):
    fpr, tpr, thresholds = roc_curve(targets[:,i],prepredictions[:,i])
    #print(AOC[i])
    #print(AOC[i][1:])
    #print(x)
    #plt.plot(x,y, '.')
    plt.plot(fpr,tpr,'.')
    x = [0,1]
    y = [0,1]
    plt.plot(x,y)
    plt.title(Highlevel_list[i])
    plt.figure(1).axes[0].set_facecolor("#ffffffff")
    plt.figure(1).axes[0].set_position([0.125000, 0.125000, 0.775000, 0.755000])
    plt.figure(1).axes[0].set_xlabel("FPR")
    plt.figure(1).axes[0].set_ylabel("TPR")
    plt.figure(1).axes[0].spines['right'].set_visible(False)
    plt.figure(1).axes[0].spines['top'].set_visible(False)
    
    ###Find and draw line paralle to digonal
    print(len(fpr))
    count_number_of_consecutiv_point_with_slope_below_digonal = 0
    point_found = False
    first = 100
    count = 0
    for index in range(len(fpr)):
        if count < first:
            count += 1
            pass
    
        #calc change in x and y over last 5 points    
        else:
            
            delta_x = fpr[index] - fpr[index-first]
            delta_y = tpr[index] - tpr[index-first]
            if delta_y/delta_x < 1:
                print((fpr[index],tpr[index]))
                print(thresholds[index])
                best_thresholds.append(thresholds[index])
                #print(delta_y/delta_x)
                a = delta_y/delta_x
                b = -(a * fpr[index]) + tpr[index]
                #print(b)
                #print(a+b)
                #print(delta_x)
                #print(delta_y)
                break
    plt.plot(fpr[index],tpr[index],'r+',markersize=15)
    x = [0,1]
    y = [b,a+b]
    plt.plot(x,y)
    print(f'./figue/{Highlevel_list[i]}.png')
    #plt.set(xlim=(0, 1), ylim=(0, 1))
    plt.savefig(f'./figue/{Highlevel_list[i]}.png')
    plt.clf()
    #break
    #print(f'threshold = {threshold}')
    #print(((prepredictions[i,:] < threshold).sum().item())/tensor_row_length)



5995
(0.20989579641312822, 0.7769365959172637)
0.38604096
./figue/Nucleus.png
6689
(0.2538650484034099, 0.8085356303837118)
0.41404262
./figue/Cytoplasm.png
1596
(0.06125258086717137, 0.9292543021032504)
0.06746229
./figue/Extracellular.png
1996
(0.08756773336059707, 0.8012358393408857)
0.12850192
./figue/Mitochondrion.png
3477
(0.11410235492467505, 0.7090150786012192)
0.1690034
./figue/Cell membrane.png
2352
(0.1750436735712503, 0.7760381211708646)
0.046195935
./figue/Endoplasmic reticulum.png
890
(0.08465889861238698, 0.9123020706455542)
0.01522767
./figue/Plastid.png
1967
(0.2768878718535469, 0.7336787564766839)
0.0437024
./figue/Golgi apparatus.png
2286
(0.38515502354788067, 0.7919642857142857)
0.0381393
./figue/Lysosome_Vacuole.png
762
(0.23777767341379796, 0.7345971563981043)
0.007232291
./figue/Peroxisome.png


<Figure size 432x288 with 0 Axes>

<img src="./figue/Nucleus.png">
<img src="./figue/Cytoplasm.png">
<img src="./figue/Extracellular.png">
<img src="./figue/Mitochondrion.png">
<img src="./figue/Cell membrane.png">
<img src="./figue/Endoplasmic reticulum.png">
<img src="./figue/Plastid.png">
<img src="./figue/Golgi apparatus.png">
<img src="./figue/Lysosome_Vacuole.png">
<img src="./figue/Peroxisome.png">

In [86]:
best_thresholds

[0.38604096,
 0.41404262,
 0.06746229,
 0.12850192,
 0.1690034,
 0.046195935,
 0.01522767,
 0.0437024,
 0.0381393,
 0.007232291]

In [87]:
prepredictions.size()

torch.Size([21504, 10])

In [88]:
Predic_new_threshold = torch.empty(prepredictions.size())

In [89]:
def Pred_with_threshold(tensor_row_input, threshold_list, tensor_row_output):
    Noneprediction = True
    distance_from_threshold = []   #only used if Noneprediction = True
    for index in range(len(threshold_list)):
        if tensor_row_input[index] > threshold_list[index]:
            tensor_row_output[index] = 1
            Noneprediction = False
        else:
            tensor_row_output[index] = 0
            distance_from_threshold.append(threshold_list[index] - tensor_row_input[index])
    if Noneprediction:
        tensor_row_output[distance_from_threshold.index(min(distance_from_threshold))] = 1
        return tensor_row_output
    else:
        return tensor_row_output     
        
    

In [90]:
for index in range(prepredictions.size()[0]):
    Predic_new_threshold[index,:] = Pred_with_threshold(prepredictions[index,:], best_thresholds, Predic_new_threshold[index,:])

In [91]:
Predic_new_threshold

tensor([[1., 1., 0.,  ..., 1., 1., 0.],
        [0., 1., 0.,  ..., 1., 1., 0.],
        [0., 1., 0.,  ..., 1., 1., 0.],
        ...,
        [1., 0., 0.,  ..., 0., 1., 1.],
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.]])

In [92]:
confusionmatrix = np.zeros((4,10), dtype=int)
print(confusionmatrix)
print(prediction.size()[0] == targets.size()[0])

# Make a confusionmattix that contains (in rows):
# 1. count of number of times each positive label (1) was correctly predicted labels.
# 2. count of number of times each negativ label (0) was correctly predicted labels. 
# 3. the number of time each label was predicted, but was not there
# 4. the number of times each label was there, but was not predicted.

# This was done of each of the 10 sublocation

for i in range(prediction.size()[1]):
    for j in range(prediction.size()[0]):
        # 1.
        if Predic_new_threshold[j,i] == 1 and targets[j,i] == 1:
            confusionmatrix[0,i] += 1
        # 2.
        elif Predic_new_threshold[j,i] == 0 and targets[j,i] == 0:
            confusionmatrix[1,i] += 1
        # 3.
        elif Predic_new_threshold[j,i] == 1 and targets[j,i] == 0:
            confusionmatrix[2,i] += 1
        elif Predic_new_threshold[j,i] == 0 and targets[j,i] == 1:
            confusionmatrix[3,i] += 1

confusionmatrix

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
True


array([[ 5747,  6195,  2429,  1556,  2210,  1140,   749,   708,   887,
          155],
       [11147, 10329, 17732, 17850, 16290, 16529, 18933, 14853, 12535,
        16231],
       [ 2960,  3513,  1157,  1712,  2097,  3506,  1750,  5686,  7849,
         5062],
       [ 1650,  1467,   186,   386,   907,   329,    72,   257,   233,
           56]])

In [93]:
# Make a confusionmattix that contains (in rows):
# 1. count of number of times each positive label (1) was correctly predicted labels.
# 2. count of number of times each negativ label (0) was correctly predicted labels. 
# 3. the number of time each label was predicted, but was not there
# 4. the number of times each label was there, but was not predicted.

# This was done of each of the 10 sublocation

for i in range(4):
    if i == 0:
        print('TP',end='\t')
    elif i == 1:
        print('TN',end='\t')
    elif i == 2:
        print('FP',end='\t')
    elif i == 3:
        print('FN',end='\t')
    
    for j in range(len(Highlevel_list)):
        print(confusionmatrix[i,j],end='\t')
    #print(confusionmatrix_Nucleus_Cytoplasm[i],end='\t')
    print()

TP	5747	6195	2429	1556	2210	1140	749	708	887	155	
TN	11147	10329	17732	17850	16290	16529	18933	14853	12535	16231	
FP	2960	3513	1157	1712	2097	3506	1750	5686	7849	5062	
FN	1650	1467	186	386	907	329	72	257	233	56	


In [94]:
print('Precision')
for j in range(len(Highlevel_list)):
    print(f'{confusionmatrix[0,j]/(confusionmatrix[0,j]+confusionmatrix[2,j]):.3f}',end='\t')
print()
print('Recall')
for j in range(len(Highlevel_list)):
    print(f'{confusionmatrix[0,j]/(confusionmatrix[0,j]+confusionmatrix[3,j]):.3f}',end='\t')
print() 
print('Accuracy')
for j in range(len(Highlevel_list)):
    Tp = confusionmatrix[0,j]
    Tn = confusionmatrix[1,j]
    acc = (Tp+Tn) / (confusionmatrix[:,j].sum())
    print(f'{acc:.3f}',end='\t')
    
    
print() 
print('F1')
for j in range(len(Highlevel_list)):
    p = confusionmatrix[0,j]/(confusionmatrix[0,j]+confusionmatrix[2,j])
    r = confusionmatrix[0,j]/(confusionmatrix[0,j]+confusionmatrix[3,j])
    print(f'{2*p*r/(p+r):.3f}',end='\t')

Precision
0.660	0.638	0.677	0.476	0.513	0.245	0.300	0.111	0.102	0.030	
Recall
0.777	0.809	0.929	0.801	0.709	0.776	0.912	0.734	0.792	0.735	
Accuracy
0.786	0.768	0.938	0.902	0.860	0.822	0.915	0.724	0.624	0.762	
F1
0.714	0.713	0.783	0.597	0.595	0.373	0.451	0.192	0.180	0.057	

In [95]:
precision_recall_curve(targets,prepredictions)

ValueError: multilabel-indicator format is not supported

In [ ]:
#https://scikit-learn.org/stable/auto_examples/model_selection/plot_precision_recall.html
'''
# For each class
precision = dict()
recall = dict()
average_precision = dict()
for i in range(n_classes):
    precision[i], recall[i], _ = precision_recall_curve(Y_test[:, i],
                                                        y_score[:, i])
    average_precision[i] = average_precision_score(Y_test[:, i], y_score[:, i])

# A "micro-average": quantifying score on all classes jointly
precision["micro"], recall["micro"], _ = precision_recall_curve(Y_test.ravel(),
    y_score.ravel())
average_precision["micro"] = average_precision_score(Y_test, y_score,
                                                     average="micro")
print('Average precision score, micro-averaged over all classes: {0:0.2f}'
      .format(average_precision["micro"]))
'''

In [114]:
precision = dict()
recall = dict()
average_precision = dict()

for i in range(targets.size()[1]):
    precision[Highlevel_list[i]], recall[Highlevel_list[i]], _ = precision_recall_curve(targets[:, i],
                                                        prepredictions[:, i])
    average_precision[Highlevel_list[i]] = average_precision_score(targets[:, i], prepredictions[:, i])
    
    plt.title(Highlevel_list[i])
    plt.plot(recall[Highlevel_list[i]],precision[Highlevel_list[i]])
    plt.figure(1).axes[0].set_xlabel("Recall")
    plt.figure(1).axes[0].set_ylabel("Precision")
    plt.savefig(f'./figue/{Highlevel_list[i]}Precision_Recall.png')
    plt.clf()

<Figure size 432x288 with 0 Axes>

Nucleus','Cytoplasm','Extracellular','Mitochondrion','Cell membrane','Endoplasmic reticulum','Plastid','Golgi apparatus','Lysosome_Vacuole','Peroxisome'

<img src="./figue/NucleusPrecision_Recall.png">
<img src="./figue/CytoplasmPrecision_Recall.png">
<img src="./figue/ExtracellularPrecision_Recall.png">
<img src="./figue/MitochondrionPrecision_Recall.png">
<img src="./figue/Cell membranePrecision_Recall.png">
<img src="./figue/Endoplasmic reticulumPrecision_Recall.png">
<img src="./figue/PlastidPrecision_Recall.png">
<img src="./figue/Golgi apparatusPrecision_Recall.png">
<img src="./figue/Lysosome_VacuolePrecision_Recall.png">
<img src="./figue/PeroxisomePrecision_Recall.png">
