In [1]:
import torch
import numpy as np

In [13]:
prediction = torch.load('../hpc-tensors/Best_prediction_1.pt')
prediction = torch.cat((prediction,torch.load('../hpc-tensors/Best_prediction_2.pt')),dim=0)
prediction = torch.cat((prediction,torch.load('../hpc-tensors/Best_prediction_3.pt')),dim=0)
prediction = torch.cat((prediction,torch.load('../hpc-tensors/Best_prediction_4.pt')),dim=0)

targets = torch.load('../hpc-tensors/Targes_1.pt')
targets = torch.cat((targets,torch.load('../hpc-tensors/Targes_2.pt')),dim=0)
targets = torch.cat((targets,torch.load('../hpc-tensors/Targes_3.pt')),dim=0)
targets = torch.cat((targets,torch.load('../hpc-tensors/Targes_4.pt')),dim=0)

In [14]:
print(prediction.size())
print(targets.size())

torch.Size([21504, 10])
torch.Size([21504, 10])


In [22]:
prediction[:,0:1].sum()

tensor(1864)

In [38]:
for i in range(prediction.size()[1]):
    print(f'Pred:\t{prediction[:,i:i+1].sum()}')
    print(f'Target:\t{targets[:,i:i+1].sum()}')

Pred:	6663
Target:	7397
Pred:	8878
Target:	7662
Pred:	2808
Target:	2615
Pred:	1841
Target:	1942
Pred:	2634
Target:	3117
Pred:	967
Target:	1469
Pred:	767
Target:	821
Pred:	199
Target:	965
Pred:	83
Target:	1120
Pred:	4
Target:	211


In [45]:
confusionmatrix = np.zeros((4,10), dtype=int)
print(confusionmatrix)
print(prediction.size()[0] == targets.size()[0])

# Make a confusionmattix that contains (in rows):
# 1. count of number of times each positive label (1) was correctly predicted labels.
# 2. count of number of times each negativ label (0) was correctly predicted labels. 
# 3. the number of time each label was predicted, but was not there
# 4. the number of times each label was there, but was not predicted.

# This was done of each of the 10 sublocation

for i in range(prediction.size()[1]):
    for j in range(prediction.size()[0]):
        # 1.
        if prediction[j,i] == 1 and targets[j,i] == 1:
            confusionmatrix[0,i] += 1
        # 2.
        elif prediction[j,i] == 0 and targets[j,i] == 0:
            confusionmatrix[1,i] += 1
        # 3.
        elif prediction[j,i] == 1 and targets[j,i] == 0:
            confusionmatrix[2,i] += 1
        elif prediction[j,i] == 0 and targets[j,i] == 1:
            confusionmatrix[3,i] += 1

confusionmatrix

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
True


array([[ 4862,  5856,  2315,  1347,  1820,   485,   623,   103,    25,
            3],
       [12306, 10820, 18396, 19068, 17573, 19553, 20539, 20443, 20326,
        21292],
       [ 1801,  3022,   493,   494,   814,   482,   144,    96,    58,
            1],
       [ 2535,  1806,   300,   595,  1297,   984,   198,   862,  1095,
          208]])

In [77]:
Highlevel_list = ['Nucleus','Cytoplasm','Extracellular','Mitochondrion','Cell membrane','Endoplasmic reticulum','Plastid','Golgi apparatus','Lysosome/Vacuole','Peroxisome']
    
#for j in range(len(Highlevel_list)):
#    print(Highlevel_list[j],end='\t')
for i in range(4):
    for j in range(len(Highlevel_list)):
        print(confusionmatrix[i,j],end='\t')
    print()

4862	5856	2315	1347	1820	485	623	103	25	3	
12306	10820	18396	19068	17573	19553	20539	20443	20326	21292	
1801	3022	493	494	814	482	144	96	58	1	
2535	1806	300	595	1297	984	198	862	1095	208	


In [60]:
Highlevel_list = ['Nucleus','Cytoplasm','Extracellular','Mitochondrion','Cell membrane','Endoplasmic reticulum','Plastid','Golgi apparatus','Lysosome/Vacuole','Peroxisome']
    
#for j in range(len(Highlevel_list)):
#    print(Highlevel_list[j],end='\t')
for i in [0,2,3]:
    for j in range(len(Highlevel_list)):
        print(confusionmatrix[i,j],end='\t')
    print()

# 1. Correctly predicted to be precent
# 2. the number of time each label was predicted, but was not there
# 3. the number of times each label was there, but was not predicted.

4862	5856	2315	1347	1820	485	623	103	25	3	
1801	3022	493	494	814	482	144	96	58	1	
2535	1806	300	595	1297	984	198	862	1095	208	


In [59]:
for j in range(len(Highlevel_list)):

    print(Highlevel_list[j],end=': ')

Nucleus: Cytoplasm: Extracellular: Mitochondrion: Cell membrane: Endoplasmic reticulum: Plastid: Golgi apparatus: Lysosome/Vacuole: Peroxisome: 

In [63]:
count_number_pred = []
count_number_targets = []
for loc_count in range(10):
    count_number_pred.append(0)
    count_number_targets.append(0)


for i in range(prediction.size()[0]):
    for loc_count in range(10):
        if prediction[i].sum() == loc_count:
            count_number_pred[loc_count] += 1
        if targets[i].sum() == loc_count:
            count_number_targets[loc_count] += 1

In [64]:
count_number_pred

[0, 18166, 3336, 2, 0, 0, 0, 0, 0, 0]

In [65]:
count_number_targets

[0, 16418, 4495, 471, 102, 18, 0, 0, 0, 0]

In [85]:
print('Precision')
for j in range(len(Highlevel_list)):
    print(f'{confusionmatrix[0,j]/(confusionmatrix[0,j]+confusionmatrix[2,j]):.3f}',end='\t')
print()
print('Recall')
for j in range(len(Highlevel_list)):
    print(f'{confusionmatrix[0,j]/(confusionmatrix[0,j]+confusionmatrix[3,j]):.3f}',end='\t')
print() 
print('Accuracy')
for j in range(len(Highlevel_list)):
    Tp = confusionmatrix[0,j]
    Tn = confusionmatrix[1,j]
    acc = (Tp+Tn) / (confusionmatrix[:,j].sum())
    print(f'{acc:.3f}',end='\t')
    
    
print() 
print('F1')
for j in range(len(Highlevel_list)):
    p = confusionmatrix[0,j]/(confusionmatrix[0,j]+confusionmatrix[2,j])
    r = confusionmatrix[0,j]/(confusionmatrix[0,j]+confusionmatrix[3,j])
    print(f'{2*p*r/(p+r):.3f}',end='\t')


Precision
0.730	0.660	0.824	0.732	0.691	0.502	0.812	0.518	0.301	0.750	
Recall
0.657	0.764	0.885	0.694	0.584	0.330	0.759	0.107	0.022	0.014	
Accuracy
0.798	0.775	0.963	0.949	0.902	0.932	0.984	0.955	0.946	0.990	
F1
0.692	0.708	0.854	0.712	0.633	0.398	0.785	0.177	0.042	0.028	

In [83]:
confusionmatrix[:,0]

array([ 4862, 12306,  1801,  2535])